modLoader="javafml"
loaderVersion="[41,)"
issueTrackerURL = "https://github.com/MerchantPug/bovines-and-buttercups/issues"
license="MIT"

[[mods]]
modId="bovinesandbuttercups"
version="${file.jarVersion}"
displayName="Bovines and Buttercups"
logoFile="bovinesandbuttercups.png"
authors="MerchantPug"
credits="SpiderKolo"
description='''
Placeholder
'''
[[dependencies.bovinesandbuttercups]]
    modId="forge"
    mandatory=true
    versionRange="[41.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bovinesandbuttercups]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
