modLoader="javafml"
loaderVersion="[41,)"
issueTrackerURL = "https://github.com/MerchantPug/bovines-and-buttercups/issues"
license="MIT"

[[mods]]
modId="bovinesandbuttercups"
version="${file.jarVersion}"
displayName="Bovines and Buttercups"
logoFile="bovinesandbuttercups.png"
updateJSONURL = "https://api.modrinth.com/updates/BDg6nMn3/forge_updates.json"
authors="MerchantPug"
credits="SpiderKolo"
description='''
A new take on the Moobloom and other bovines.
'''

[[dependencies.bovinesandbuttercups]]
    modId="forge"
    mandatory=true
    versionRange="[45.0.23,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bovinesandbuttercups]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
