modLoader="javafml"
loaderVersion="[41,)"
issueTrackerURL = "https://github.com/MerchantPug/bovines-and-buttercups/issues"
license="LGPL-3.0-only"

[[mods]]
modId="bovinesandbuttercups"
version="${file.jarVersion}"
displayName="Bovines and Buttercups"
logoFile="bovinesandbuttercups.png"
authors="MerchantPug"
credits="SpiderKolo"
description='''
A new take on the Moobloom and other bovines.
'''
[[dependencies.bovinesandbuttercups]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bovinesandbuttercups]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
