name: Maven Publish

on: [workflow_dispatch]

env:
  ORG_GRADLE_PROJECT_merchantpugUsername: ${{ secrets.MAVEN_NAME }} # token
  ORG_GRADLE_PROJECT_merchantpugPassword: ${{ secrets.MAVEN_TOKEN }} # password
  ENVIRONMENT: production

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Set up JDK
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Clean Gradle
        run: ./gradlew clean
      - name: Publish Artifacts
        run: ./gradlew build publish